# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("calculator.proto", :syntax => :proto3) do
    add_message "Number" do
      optional :value, :float, 1
    end
  end
end

Number = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Number").msgclass
